version: '3.7'

services:
  db-teste:
    image: postgres
    container_name: postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Medex
    networks:
      - localdev
    ports:
      - "5433:5432"

  medex:
    container_name: Medex
    environment:
      - PORT=5000
    ports:
      - 5000:5000 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - "db-teste"

    networks:
      - localdev

networks:
  localdev:
    driver: bridge

#version: '3.7'
#services:
#  db:
#    image: mysql:8.0.30
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'Medex'
#       So you don't have to use root, but you can if you like
#      MYSQL_USER: 'root'
#       You can use whatever password you like
#      MYSQL_PASSWORD: '1234'
#       Password for root access
#      MYSQL_ROOT_PASSWORD: '1234'
#    ports:
#       <Port exposed> : < MySQL Port running inside container>
#      - '3305:3305'
#  medex:
#    container_name: Medex
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#     - "db"
#    networks:
#      - localdev

#networks:
#  localdev:
#    driver: bridge
#    expose:
#       Opens port 3306 on the container
#      - '3305'
#       Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
# Names our volume
#volumes:
#  my-db:

